### ISSUE TITLE
page：about me

### ISSUE THREAD

**Issue by ghost** [SuperKieran/TKL#36]
can you tell me how to add "about me" page?

**Comment by Jmq14** [comment]
+1. I've tried use `hexo new page "about"` but errors occur when generating. The messages are below:

```
Unhandled rejection TypeError: /Users/mengqingjiang/GitHub/jmq14.github.io/themes/TKL/layout/page.ejs:1
 >> 1| <%- partial('casper/about', {post: page}) %>
    2| 

/Users/mengqingjiang/GitHub/jmq14.github.io/themes/TKL/layout/casper/about.ejs:25
    23|                     <div class="born">Now</div>
    24|                     <div class="dot_bt"></div>
 >> 25|                     <% theme.timeline.forEach(function(item){ %>
    26|                         <div class="timeline-entry">
    27|                             <div class="timeline-entry-inner">
    28|                                 <div class="timeline-icon wow fadeInUp" data-wow-delay="0.2s">

Cannot read property 'forEach' of undefined
    at eval (eval at <anonymous> (/Users/mengqingjiang/GitHub/jmq14.github.io/node_modules/hexo-renderer-ejs/node_modules/ejs/lib/ejs.js:242:14), <anonymous>:30:938)
    at eval (eval at <anonymous> (/Users/mengqingjiang/GitHub/jmq14.github.io/node_modules/hexo-renderer-ejs/node_modules/ejs/lib/ejs.js:242:14), <anonymous>:30:1813)
    at /Users/mengqingjiang/GitHub/jmq14.github.io/node_modules/hexo-renderer-ejs/node_modules/ejs/lib/ejs.js:255:15
    at Object.exports.render (/Users/mengqingjiang/GitHub/jmq14.github.io/node_modules/hexo-renderer-ejs/node_modules/ejs/lib/ejs.js:293:13)
    at Hexo.<anonymous> (/Users/mengqingjiang/GitHub/jmq14.github.io/node_modules/hexo-renderer-ejs/index.js:5:14)
    at Render.renderSync (/Users/mengqingjiang/GitHub/jmq14.github.io/node_modules/hexo/lib/hexo/render.js:87:23)
    at View.renderSync (/Users/mengqingjiang/GitHub/jmq14.github.io/node_modules/hexo/lib/theme/view.js:50:29)
    at Object.partial (/Users/mengqingjiang/GitHub/jmq14.github.io/node_modules/hexo/lib/plugins/helper/partial.js:42:19)
    at eval (eval at <anonymous> (/Users/mengqingjiang/GitHub/jmq14.github.io/node_modules/hexo-renderer-ejs/node_modules/ejs/lib/ejs.js:242:14), <anonymous>:30:35)
    at eval (eval at <anonymous> (/Users/mengqingjiang/GitHub/jmq14.github.io/node_modules/hexo-renderer-ejs/node_modules/ejs/lib/ejs.js:242:14), <anonymous>:30:85)
    at /Users/mengqingjiang/GitHub/jmq14.github.io/node_modules/hexo-renderer-ejs/node_modules/ejs/lib/ejs.js:255:15
    at Object.exports.render (/Users/mengqingjiang/GitHub/jmq14.github.io/node_modules/hexo-renderer-ejs/node_modules/ejs/lib/ejs.js:293:13)
    at Hexo.<anonymous> (/Users/mengqingjiang/GitHub/jmq14.github.io/node_modules/hexo-renderer-ejs/index.js:5:14)
    at Hexo.tryCatcher (/Users/mengqingjiang/GitHub/jmq14.github.io/node_modules/hexo/node_modules/bluebird/js/main/util.js:26:23)
    at Hexo.<anonymous> (/Users/mengqingjiang/GitHub/jmq14.github.io/node_modules/hexo/node_modules/bluebird/js/main/method.js:15:34)
    at /Users/mengqingjiang/GitHub/jmq14.github.io/node_modules/hexo/lib/hexo/render.js:51:21
    at tryCatcher (/Users/mengqingjiang/GitHub/jmq14.github.io/node_modules/hexo/node_modules/bluebird/js/main/util.js:26:23)
    at Promise._settlePromiseFromHandler (/Users/mengqingjiang/GitHub/jmq14.github.io/node_modules/hexo/node_modules/bluebird/js/main/promise.js:507:31)
    at Promise._settlePromiseAt (/Users/mengqingjiang/GitHub/jmq14.github.io/node_modules/hexo/node_modules/bluebird/js/main/promise.js:581:18)
    at Promise._settlePromiseAtPostResolution (/Users/mengqingjiang/GitHub/jmq14.github.io/node_modules/hexo/node_modules/bluebird/js/main/promise.js:245:10)
    at Async._drainQueue (/Users/mengqingjiang/GitHub/jmq14.github.io/node_modules/hexo/node_modules/bluebird/js/main/async.js:128:12)
    at Async._drainQueues (/Users/mengqingjiang/GitHub/jmq14.github.io/node_modules/hexo/node_modules/bluebird/js/main/async.js:133:10)
    at Immediate.Async.drainQueues (/Users/mengqingjiang/GitHub/jmq14.github.io/node_modules/hexo/node_modules/bluebird/js/main/async.js:15:14)
    at runCallback (timers.js:574:20)
    at tryOnImmediate (timers.js:554:5)
    at processImmediate [as _immediateCallback] (timers.js:533:5)
```

**Comment by SuperKieran** [comment]
`touch about.md` in /source/  

Here is a simple `about.md` example:  
``` markdown 
### About Me
write something
```

**Comment by Jmq14** [comment]
I solved my problem by adding `timeline` part in `_config.yml` back (I deleted it long ago since I thought it was useless...). Thanks for the advice by @SuperKieran !
